version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cinetrack_db
    environment:
      POSTGRES_USER: cinetrack
      POSTGRES_PASSWORD: cinetrack123
      POSTGRES_DB: cinetrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: